version: 2.1
orbs:
  win: circleci/windows@2.4.0
  slack: circleci/slack@4.4.0
jobs:
  publish-windows64:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: scripts/publish-windows.bat
  build-windows64:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: scripts/build-windows.bat
  publish-linux64:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - run: scripts/publish-linux-circleci.sh
  build-linux64:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - run: scripts/build-linux-circleci.sh
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
workflows:
  version: 2
  linux64:
    jobs:
      - publish-linux64:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-linux64:
          filters:
            branches:
              only: master
  windows64:
    jobs:
      - publish-windows64:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-windows64:
          filters:
            branches:
              only: master
