version: 2.1
orbs:
  win: circleci/windows@5.0.0
  slack: circleci/slack@4.10.1
  gh: circleci/github-cli@2.0
jobs:
  build-linux:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: Building
          command: scripts/build-linux-circleci.sh
      - persist_to_workspace:
          root: dist
          paths:
            - cleepbus/*
            - ./*.txt
  build-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: Building
          command: scripts/build-windows.bat
      - persist_to_workspace:
          root: dist
          paths:
            - cleepbus/*
            - ./*.txt
  build-macos:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: Building
          command: scripts/build-macos.sh
      - persist_to_workspace:
          root: dist
          paths:
            - cleepbus/*
            - ./*.txt
  package:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - attach_workspace:
          at: dist
      - run:
          name: Packaging
          command: scripts/package.sh
      - persist_to_workspace:
          root: package
          paths:
            - ./*.zip
  publish:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - attach_workspace:
          at: package
      - gh/setup
      - run:
          name: Publishing
          command: scripts/publish.sh
  notify:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: Slack notification
          command: source scripts/notify.sh
          environment:
            VCS_TYPE: << pipeline.project.type >>
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  version: 2
  test:
    jobs:
      - build-linux
          filters:
            tags:
              only: /.*/
            branches:
              only: master
  linux:
    jobs:
      - build-linux
      - package:
          requires:
            - build-linux
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - package
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  windows:
    jobs:
      - build-windows
      - package:
          requires:
            - build-windows
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - package
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  macos:
    jobs:
      - build-macos
      - package:
          requires:
            - build-macos
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - package
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
