version: 2.1
orbs:
  win: circleci/windows@5.1.0
  slack: circleci/slack@5.1.1
  gh: circleci/github-cli@2.7.0
jobs:
  build-linux:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run:
          name: Building
          command: scripts/build-linux-circleci.sh
      - persist_to_workspace:
          root: dist
          paths:
            - cleepbus/*
            - ./*.txt
  build-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: Building
          command: scripts/build-windows.bat
      - persist_to_workspace:
          root: dist
          paths:
            - cleepbus/*
            - ./*.txt
  build-macos:
    macos:
      xcode: 16.0.0
    resource_class: macos.m1.medium.gen1
    steps:
      - run:
          name: Install certificate
          command: |
            curl -sS --location --fail --output cert.p12 $CSC_LINK
            ls -l
            echo "create-keychain"
            security create-keychain -p "" build.keychain
            echo "default-keychain"
            security default-keychain -s build.keychain
            echo "unlock-keychain"
            security unlock-keychain -p "" build.keychain
            echo "import"
            security import cert.p12 -k build.keychain -P "$CSC_KEY_PASSWORD" -T /usr/bin/codesign
            echo "set-key-partition-list"
            security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
      - checkout
      - run:
          name: Building
          command: scripts/build-macos.sh
      - persist_to_workspace:
          root: dist
          paths:
            - cleepbus/*
            - ./*.txt
  package:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run:
          name: Packaging
          command: scripts/package.sh
      - persist_to_workspace:
          root: package
          paths:
            - ./*.zip
  publish:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - attach_workspace:
          at: package
      - gh/setup
      - run:
          name: Publishing
          command: scripts/publish.sh
  notify:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run:
          name: Slack notification
          command: source scripts/notify.sh
          environment:
            VCS_TYPE: << pipeline.project.type >>
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  version: 2
  linux:
    jobs:
      - build-linux:
          filters:
            tags:
              only: /.*/
            branches:
              only: master
      - package:
          requires:
            - build-linux
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - package
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  windows:
    jobs:
      - build-windows:
          filters:
            tags:
              only: /.*/
            branches:
              only: master
      - package:
          requires:
            - build-windows
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - package
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  macos:
    jobs:
      - build-macos:
          filters:
            tags:
              only: /.*/
            branches:
              only: master
      - package:
          requires:
            - build-macos
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - package
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
