version: 2.1
orbs:
  win: circleci/windows@5.0.0
  slack: circleci/slack@4.10.1
  gh: circleci/github-cli@2.0
jobs:
  build-linux:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run: scripts/build-linux-circleci.sh
      - persist_to_workspace:
          root: dist
          paths:
            - cleepbus/*
            - version.txt
            - platform.txt
  package:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - attach_workspace:
          at: dist
      - run: find 
      - run: |
          VERSION=`cat dist/version.txt`
          PLATFORM=`cat dist/platform.txt`
          ARCHIVE="cleepbus-v$VERSION-$PLATFORM-x64.zip"
          mkdir package
          cd dist/cleepbus
          zip -q -8 -r "../../package/$ARCHIVE" .
          echo "Package $ARCHIVE built successfully"
          cd ../../package
          ls -l
      - persist_to_workspace:
          root: package
          paths:
            - "$ARCHIVE"
  publish:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - attach_workspace:
          at: package
      - gh/setup
      - run: scripts/publish.sh

  notify:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  version: 2
  linux:
    jobs:
      - build-linux:
          filters:
            branches:
              only: master
      - package:
          requires:
            - build-linux
      - publish:
          requires:
            - package
